// Generated by binpac_quickstart

#include "plugin/Plugin.h"

#include "TELNET.h"

namespace plugin {
namespace CBro_TELNET {

class Plugin : public plugin::Plugin {
public:
	plugin::Configuration Configure()
		{
		AddComponent(new ::analyzer::Component("TELNET",
		             ::analyzer::telnet::TELNET_Analyzer::InstantiateAnalyzer));

		plugin::Configuration config;
		config.name = "CBro::TELNET";
		config.description = "telnet analyzer";
		return config;
		}
} plugin;

}
}
